[package]
name = "hmy-web3"
version = "0.1.0"
edition = "2018"

[dependencies]
futures = "0.3.5"
futures-timer = "3.0"
jsonrpc-core = "18.0"
serde_json = "1.0.57"
tokio = { version = "1.0", features = ["full"] }
web3 = "0.17.0"

[dependencies.serde]
version = "1.0.90"
features = ["derive"]
